### ISSUE TITLE
You are missing AMD Crash Defender

### ISSUE THREAD

**Issue by mirh** [Wagnard/display-drivers-uninstaller#58] opened 2021-01-05 23:20 UTC
Aka AMDLOG aka amdfendr.

**Comment by Wagnard** [comment] 2021-01-05 23:34
Strange, I do remove "amdfendr" and "AMD Crash Defender Service" (visible in the services.cfg file)

May I have a DDU log to see why it didn't catch it up on your end ?

**Comment by Wagnard** [comment] 2021-01-05 23:58
@mirh I have run DDU 18.0.3.5 on my AMD card for testing and can confirm that "amdfendr" is removed. So a Log would really help

**Comment by mirh** [comment] 2021-01-06 00:48
[Here you are](https://github.com/Wagnard/display-drivers-uninstaller/files/5773300/2021-01-05__23-57-22_DDULog.zip) (thanks god they are enabled by default, otherwise I really wouldn't have been able to reproduce anything anymore now that I switched my gpu).

**Comment by Wagnard** [comment] 2021-01-06 13:33
I see in the log that you were not in safe mode and that could have been the cause of the issue. I can clearly see in the log that DDU tried to remove it but failed.
So  I guess no in safe mode was the reason. and since I cant repro and you cant test that anymore, ill close the issue but thanks for pointing it out to me.

**Closed as completed by Wagnard** 2021-01-06 13:33 UTC
Labels: no repro atm.

**Comment by mirh** [comment] 2021-01-06 14:47
I always strive for safe mode, but since I switched the whole computer actually, every time I press F8 for the windows 7 boot options menu the framebuffer corrupts. I'm using CSM but maybe there's still some shenanigan with the the GOP driver or whatnot. 

So before installing the optimus drivers I still wanted to clean my system (funnily enough, the AMD uninstaller completely forgot that), and I stick to "normal boot". Can't you even reproduce the thing with that?

**Comment by Wagnard** [comment] 2021-01-06 15:21
I cant repro on a Windows 10 system with the AMD card. Its possible this is something that happen on normal mode with Windows 7.

If safe mode is not possible on your end, you can actually clean in normal mode, reboot, and clean again. This *should* be as efficient as safe mode.
